name: "Build & Publish Tauri App"
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Add macOS targets
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
      - name: Install dependencies
        run: npm ci
      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0.5.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: .
          tagName: ${{ github.ref_name }}
          releaseName: "Can I Run This ${{ github.ref_name }}"
          releaseBody: "Cross-platform build"
          args: >-
            ${{ matrix.os == 'macos-latest' && '--target universal-apple-darwin' || '' }}
